-- =====================================================
-- MindShift Database Schema (PostgreSQL)
-- This is auto-generated by Hibernate (ddl-auto=update)
-- Kept here as a readable reference / for manual setup
-- =====================================================

CREATE TABLE users (
    id              BIGSERIAL PRIMARY KEY,
    name            VARCHAR(100) NOT NULL,
    email           VARCHAR(150) NOT NULL UNIQUE,
    password        VARCHAR(255) NOT NULL,
    severity        INTEGER NOT NULL DEFAULT 9,
    goal            VARCHAR(20) NOT NULL DEFAULT 'SUPERHUMAN',
    created_at      TIMESTAMP NOT NULL
);

CREATE TABLE user_impacts (
    user_id         BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    impact          VARCHAR(50)
);

CREATE TABLE daily_progress (
    id              BIGSERIAL PRIMARY KEY,
    user_id         BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    current_day     INTEGER NOT NULL DEFAULT 1,
    god_mode_score  INTEGER NOT NULL DEFAULT 0,
    started_at      TIMESTAMP NOT NULL,
    updated_at      TIMESTAMP NOT NULL
);

CREATE TABLE completed_days (
    progress_id     BIGINT NOT NULL REFERENCES daily_progress(id) ON DELETE CASCADE,
    day_number      INTEGER NOT NULL
);

CREATE TABLE journal_entries (
    id              BIGSERIAL PRIMARY KEY,
    user_id         BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    text            TEXT NOT NULL,
    intensity       INTEGER NOT NULL,
    category        VARCHAR(30) NOT NULL DEFAULT 'UNCATEGORIZED',
    created_at      TIMESTAMP NOT NULL
);
CREATE INDEX idx_journal_user ON journal_entries(user_id);

CREATE TABLE journal_tags (
    entry_id        BIGINT NOT NULL REFERENCES journal_entries(id) ON DELETE CASCADE,
    tag             VARCHAR(50)
);

CREATE TABLE tracker_entries (
    id              BIGSERIAL PRIMARY KEY,
    user_id         BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    day_key         VARCHAR(16) NOT NULL,
    awareness       INTEGER NOT NULL,
    control         INTEGER NOT NULL,
    presence        INTEGER NOT NULL,
    sleep           INTEGER NOT NULL,
    confidence      INTEGER NOT NULL,
    peace           INTEGER NOT NULL,
    created_at      TIMESTAMP NOT NULL,
    UNIQUE(user_id, day_key)
);

CREATE TABLE chat_messages (
    id              BIGSERIAL PRIMARY KEY,
    user_id         BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role            VARCHAR(10) NOT NULL,
    content         TEXT NOT NULL,
    created_at      TIMESTAMP NOT NULL
);
CREATE INDEX idx_chat_user ON chat_messages(user_id);
